# Generated by Django 5.0.4 on 2024-05-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeBinomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Binome', models.CharField(max_length=126)),
                ('Theme', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='NonDispoEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Heure', models.TimeField()),
            ],
        ),
    ]
