# Generated by Django 5.0.4 on 2024-05-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeThemes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Theme', models.CharField(max_length=126)),
                ('Specialite', models.CharField(max_length=126)),
            ],
        ),
    ]
