# Generated by Django 5.0.4 on 2024-05-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0004_rename_test_listethemes_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listethemes',
            old_name='id',
            new_name='Num',
        ),
    ]
