# Generated by Django 5.0.4 on 2024-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0005_rename_id_listethemes_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listethemes',
            old_name='Num',
            new_name='id',
        ),
        migrations.AddField(
            model_name='listethemes',
            name='Champ',
            field=models.CharField(default='1', max_length=126),
        ),
    ]
