# Generated by Django 5.0.4 on 2024-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0007_remove_listethemes_champ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listethemes',
            name='Specialite',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
