# Generated by Django 4.2.1 on 2024-04-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authentification',
            new_name='Admin',
        ),
    ]
