# Generated by Django 5.0.4 on 2024-06-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='nom',
            field=models.CharField(default='karim', max_length=120),
        ),
        migrations.AddField(
            model_name='admin',
            name='prenom',
            field=models.CharField(default='karim', max_length=120),
        ),
    ]
