# Generated by Django 5.0.4 on 2024-06-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_admin_nom_admin_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='admin',
            name='prenom',
            field=models.CharField(max_length=120),
        ),
    ]
