# Generated by Django 5.0.4 on 2024-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_alter_admin_nom_alter_admin_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nom',
            field=models.CharField(default='karim', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='prenom',
            field=models.CharField(default='karim', max_length=120),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nom',
            field=models.CharField(default='karim', max_length=120),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prenom',
            field=models.CharField(default='karim', max_length=120),
        ),
        migrations.AlterField(
            model_name='admin',
            name='nom',
            field=models.CharField(default='karim', max_length=120),
        ),
        migrations.AlterField(
            model_name='admin',
            name='prenom',
            field=models.CharField(default='karim', max_length=120),
        ),
    ]
