# Generated by Django 5.0.4 on 2024-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_student_nom_student_prenom_teacher_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='admin',
            name='prenom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='prenom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='prenom',
            field=models.CharField(max_length=120),
        ),
    ]
