# Generated by Django 4.2.1 on 2024-04-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme', models.CharField(max_length=256)),
                ('Date', models.DateTimeField()),
                ('Local', models.CharField(max_length=64)),
                ('Binome', models.CharField(max_length=256)),
                ('Encadreur', models.CharField(max_length=64)),
                ('Jury', models.CharField(max_length=64)),
            ],
        ),
    ]
