# Generated by Django 5.0.4 on 2024-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_plateforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='Date',
            field=models.CharField(max_length=256),
        ),
    ]
