# Generated by Django 5.0.4 on 2024-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=256)),
                ('Prenom', models.CharField(max_length=256)),
                ('Login', models.CharField(max_length=128)),
                ('MDP', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=256)),
                ('Prenom', models.CharField(max_length=256)),
                ('Login', models.CharField(max_length=128)),
                ('MDP', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=256)),
                ('Prenom', models.CharField(max_length=256)),
                ('Login', models.CharField(max_length=128)),
                ('MDP', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='utilisateurs',
        ),
    ]
