# Generated by Django 5.0.4 on 2024-06-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_admins_enseignants_etudiants_delete_utilisateurs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.DeleteModel(
            name='Enseignants',
        ),
        migrations.DeleteModel(
            name='Etudiants',
        ),
    ]
