# Generated by Django 5.0.4 on 2024-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('specialite', models.CharField(max_length=256)),
                ('theme', models.CharField(max_length=256)),
                ('encadreur', models.CharField(max_length=256)),
                ('president', models.CharField(max_length=256)),
                ('examinteur1', models.CharField(max_length=256)),
                ('examinteur2', models.CharField(max_length=256)),
                ('Date_debut', models.CharField(max_length=256)),
                ('Date_fin', models.CharField(max_length=256)),
                ('salle', models.CharField(max_length=256)),
            ],
        ),
    ]
