# Generated by Django 5.0.4 on 2024-06-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_soutenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soutenance',
            old_name='Date_fin',
            new_name='heure',
        ),
    ]
